theme = "Relearn"
baseURL = 'https://hmmt.ee/'
languageCode = 'en-us'
title = 'Y.HMMT'z
[params]
  alwaysopen = true
  collapsibleMenu = true
  themeVariant = 'blue'
  
[module]
  [[module.imports]]
    path = 'github.com/McShelby/hugo-theme-relearn'
