theme = "Relearn"
baseURL = 'https://hmmt.ee/'
languageCode = 'en-us'
title = 'Y.HMMT'
[params]
  [params.relearn]
    alwaysopen = true
    collapsibleMenu = true
    themeVariant = 'blue'
  
[module]
  [[module.imports]]
    path = 'github.com/McShelby/hugo-theme-relearn'
