theme = "Relearn"
baseURL = 'https://hmmt.ee/'
languageCode = 'en-us'
title = 'Y.HMMT'
alwaysopen = true
collapsibleMenu = true
  
[module]
  [[module.imports]]
    path = 'github.com/McShelby/hugo-theme-relearn'
