baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'Y.HMMT'
theme = "Relearn"
sectionPagesMenu = 'main'
[outputs]
  home = ['html', 'rss', 'print']
  section = ['html', 'rss', 'print']
  page = ['html', 'rss', 'print']
  

